token =
  "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxNiIsInNjb3BlIjoiQURNSU4gbnVsbCIsImlzcyI6IndlYnNpdGUuY29tIiwiZXhwIjoxNzUyMDM1MjEyLCJpYXQiOjE3NTIwMzE2MTIsImp0aSI6ImE5MmM1NmI4LTk2ZDgtNGVhZC05MGFlLTk4NDFkYWMzYjcyYiIsImVtYWlsIjoiYWRtaW5AYWRtaW4uY29tIn0.I-pCuiHxX5-_5T4vokfXsM41ndLlIqJcd-emEn4fhXP57caNm_f72yldmyg1iiF9HiR5jbcMUKIsjef6YMdlXQ";

localStorage.setItem("accessToken", token);
